Added next-auth 5 for authentication
TIHLDE/kontres pull request #109
Opened 2024-09-26 17:00 UTC by AleksanderEvensen

2024-09-29 12:29 UTC, MindChirp requested changes

2024-09-29 12:29 UTC, MindChirp commented on src/app/components/authTester.tsx
Navnekonvensjonen i kontres er litt ass, men vi prøver å bruke kebab casing på alle filer: `auth-tester.tsx`

2024-09-29 12:29 UTC, MindChirp commented on src/app/components/authTester.tsx
Men dette er vel bare en demokomponent, så det har ikke så mye å si

2024-09-29 12:29 UTC, MindChirp commented on src/app/layout.tsx
> +                        {/* <Header className="lg:flex hidden" /> */}
Denne må implementeres igjen. Kjipt å ikke ha en header

2024-09-29 12:29 UTC, MindChirp commented on src/auth.ts
> +        isAdmin: memberships?.results.some((r) =>
Alle gruppeledere og superadmins (index) skal ha adminstatus

2024-09-29 12:29 UTC, MindChirp commented on src/env.js
> +        NEXTAUTH_SECRET: z.string(),
fjerne NEXTAUTH_SECRET

2024-09-29 12:29 UTC, MindChirp commented on src/server/api/routers/post.ts
> +    hello: memberProcedure
Fjern denne

2024-09-29 12:29 UTC, MindChirp commented on src/server/api/routers/post.ts
Denne fila burde sannsynligvis renames til noe mer passende

2024-09-29 12:29 UTC, MindChirp commented on src/utils/apis/fetch.ts
> -export const IFetch = <T extends unknown>({ url, config }: IFetchProps) => {
Vi burde vurdere å ha en wrapper-funksjon som legger inn auth token i alle requests dersom vi kommuniserer med Lepton

2024-09-30 14:32 UTC, AleksanderEvensen commented on src/auth.ts
> +        isAdmin: memberships?.results.some((r) =>
Ikke riktig. Gruppeledere skal ikke ha full admin rettigheter på siden. De skal bare ha tilgang på sin egen side.

2024-09-30 14:46 UTC, merged